services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  app:
    image: todo-fastapi:latest
    environment:
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "${DB_NAME}"
      SECRET: "${SECRET}"
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  front:
    image: nginx:alpine
    volumes:
      - ./front:/usr/share/nginx/html:ro
    ports:
      - "5500:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

volumes:
  postgres_data:
